### ISSUE TITLE
A few notes on the network scanner

### ISSUE THREAD

**Issue by arthurwolf** [lautr3k/Smoothie-Happy#1]
First off, when the .onboard callback is called, the "board" object passed as a parameter doesn't contain the IP ( that I can see ), which is a huge handicap :)

Second, it's not very clear from the documentation that onboard, onprogress etc, are options of scan. It looks like they are methods ( sh.scanner.onboard etc ), which would probably nice to have anyway.

Thanks :)

**Comment by lautr3k** [comment]
Add ip is not a big deal (comming in the next commit).
For the chainable feature i need to refactor the network module (comming in the next version).
